#version: "3.9" considéré comme obsolète d'après le terminal

services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_PASSWORD=${POSTGRES_PW}
    - POSTGRES_DB=${POSTGRES_DB}
    - NODE_ENV=development
    - ADDRESS=0.0.0.0
    - PORT=8032
    - DATABASE_URL=${LOCAL_DATABASE_URL} #Ce bloc est en doublon (services postgres et dev) et ne devrait pas être dans le service postgres. Ca n'a pas d'incidence.
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.11.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin # volume pour persister les données de pgadmin. Le volume global remonte jusqu'ici
    restart: always

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=${LOCAL_DATABASE_URL}
    ports:
      - "8032:8032"
    environment:
      - NODE_ENV=development
      - ADDRESS=0.0.0.0
      - PORT=8032
      - DATABASE_URL=${DATABASE_URL}
      - LOCAL_DATABASE_URL=${LOCAL_DATABASE_URL}
    volumes: # on mappe le dossier local à gauche sur le dossier distant dans le volume du container à droite
      - .:/app
      - /app/node_modules
      - /app/build # évite d'écraser le build du container
    command: npm start
    depends_on:
      - postgres
    #command: npm run dev  

  prod:
    profiles:
      - prod
    build:
      context: .
      args:
        - DATABASE_URL:${LOCAL_DATABASE_URL} # Ca devrait être un égal au lieu de deux points ici. A voir si ça marche quand on lance la prod!
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production

volumes:
  postgres_data:
  pgadmin_data: # on déclare les volumes globaux. Celui-ci indique qu'on en a un qui récupère les data de pgadmin.