// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

// <reference types="node"

import "dotenv/config";
import { defineConfig } from "prisma/config";

const isDevelopment = process.env.NODE_ENV !== "production";
const databaseURL = isDevelopment ? process.env["LOCAL_DATABASE_URL"] : process.env["DATABASE_URL"];

if (!databaseURL) {
  throw new Error("DATABASE_URL is not defined");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts"
 },
  datasource: {
    url: databaseURL,
  },
});
console.log("🌼 the URL from prisma.config.ts is: ", process.env["DATABASE_URL"]);
