# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  prisma-migrate-db:
    desc: prisma migrate on local database
    cmds: 
      - docker exec back_ink_and_voices-dev-1 sh -c "npx prisma migrate dev"
      
  prisma-seed-db:
    desc: prisma seed on local database
    cmds: 
      - docker exec back_ink_and_voices-dev-1 sh -c "npx prisma db seed"

  prisma-migrate-test:
    desc: prisma migrate on test database
    cmds:
      - docker exec back_ink_and_voices-dev-1 sh -c "source /app/.env && (LOCAL_DATABASE_URL=${TEST_DATABASE} npx prisma migrate deploy)"
  
  prisma-seed-test:
    desc: prisma seed on test database
    cmds:
      - docker exec back_ink_and_voices-dev-1 sh -c 'LOCAL_DATABASE_URL=$TEST_DATABASE npx prisma db seed'

  run-tests:
    desc: run the tests
    cmds: 
      - docker exec back_ink_and_voices-dev-1 sh -c "npm run test"

