# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  # Si des tables/modèles ont été modifiées, ajoutées ou supprimées.
  prisma-migrate:
    desc: Runs prisma migrate dev to apply pending migrations to the local database
    cmds: 
      - docker exec back_ink_and_voices-dev-1 sh -c "npx prisma migrate dev"
  # Pour peupler la db avec des données par défaut (ces données sont déjà présentes en db)
  seed-db:
    desc: Seeds local database for dev
    cmds:
      - docker exec back_ink_and_voices-dev-1 sh -c "npx prisma db seed"


