name: Ink and Voices Workflow
run-name: Ink and Voices workflow is running.
on: workflow_dispatch
jobs:
  tests_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by ${{ github.event_name }}. Job running on a ${{ runner.os }} server. Branch ${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Lancer les tests
        run: npm test
      - run: echo "🍏 This job's status is ${{ job.status }}."
